version: '3'
services:
  app:
    container_name: spotter
    build:
      context: .
      dockerfile: ./Dockerfile/development/Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
     - /app/node_modules
    restart: always
    environment:
      - HOSTNAME=localhost:3000
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:4
    command: [--auth]
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    restart: always
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"