# This is a basic workflow to help you get started with Actions
name: Spotter CI Tests
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - run: |
                  rm .gitignore
                  ls -a
          - run: |
              git clone https://gist.github.com/${{ secrets.CONFIG_URI_ID }}.git
              mv ${{ secrets.CONFIG_URI_ID }}/config.ts ./src/config/env/
              rm -rf ${{ secrets.CONFIG_URI_ID }}
              ls -a
          - run: |
              git config --global user.name kumaranshu72
              git config --global user.email kumaranshu72@gmail.com
              git add .
              git commit -m "Add Config file"
          - run: npm install
          - run: npm run test-with-coverage
            env:
              CI: true
              NODE_ENV: test
